name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3

      - name: Setup the python
        uses: actions/checkout@v3

      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      
      - name: Run tests
        run: python -m pytest -v tests


      - name: upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage report
          path : |
            ./htmlcov
            ./coverage.xml