name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3

      - name: Setup the python
        uses: actions/checkout@v3

      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      
      - name: Run tests with coverage
        run: |
          python -m pytest --cov=./ --cov-report=xml --cov-report=html
          coverage report --fail-under=70 --show-missing > pytest-coverage.txt

      - name: Generate Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml